baseURL = 'https://zhouzihui123.github.io/newsite/'
languageCode = 'en-us'
theme = 'ananke'
title = '新闻合集'
publishDir="docs"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

