baseURL = 'https://example.org/'
languageCode = 'en-us'
publishDir="docs"
theme = 'ananke'
title = '新闻合集'

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

